### PR TITLE
Merge KaJuan's courses into this one

### PR DESCRIPTION
**Pull request by sbracellari**
#### Overview

The master branch of KaJuan's courses has been merged into this branch (C-22). All merge conflicts were resolved and bugs were patched. Anything that was originally in this repo that had to stay has been re-incorporated.

#### Merger

- [x] @amgoodfellow 

#### Reviewers

- [x] @nickwoodle 
- [x] @sterlingwalker

#### Notes

To test this frontend with demo data, change `is_demo` in `public/index.html` to `true`. This can also be run with the courses soffit backend (located in gitlab)

### CODE REVIEW

**Comment by nickwoodle** [comment]
I think that most of this was reviewed in KaJuan's repo. I did notice that the info cards can no be dismissed which is awesome and I will be stealing that for the faculty version of courses.  Nick work @sbracellari

**Review by nickwoodle — APPROVED** [review]
LGTM!

**Review by sterlingwalker — APPROVED** [review]
I like how you've changed the date format. Also a really fancy way of using `determineColor(course)` to handle the styling for the course cards.

Really nice updates @sbracellari !

**Review by amgoodfellow — APPROVED** [review]
I reviewed some things out of order; on a  [different review](https://github.com/Oakland-University/courses/pull/29#pullrequestreview-502914235), I had mentioned that I'm not sure what the UX will be of dismissable cards where their memory of being dismissed only lasts as long as the next page refresh. It might be a fun thing to add to sessionStorage or something, so at least it would last as long as the tab

**Pull request merged**
